version: '3.8'

services:
  mysql-dev:
    image: mysql:8.0
    container_name: sigma-gym-mysql-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sigma_gym_dev
      MYSQL_USER: sigma_user
      MYSQL_PASSWORD: sigma_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-sigmagym
    depends_on:
      - mysql-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-dev:3306/sigma_gym_dev?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires
      - SPRING_DATASOURCE_USERNAME=sigma_user
      - SPRING_DATASOURCE_PASSWORD=sigma_pass
    ports:
      - "8080:8080"

volumes:
  mysql_dev_data:
    driver: local
