spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sigma_gym_dev?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update # ⛔️ NO create-drop - Los datos persisten
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  sql:
    init:
      mode: never # No ejecutar scripts SQL automáticos

# Database Seeding Configuration
sigmagym:
  seed:
    enabled: true # Habilitar seeding en desarrollo

# Logging optimizado para desarrollo
logging:
  level:
    com.sigma.gym: DEBUG
    com.sigma.gym.security.JwtAuthenticationFilter: INFO
    org.hibernate.SQL: WARN # Solo mostrar SQL si hay problemas
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.security: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
