spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sigma_gym_dev?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Argentina/Buenos_Aires
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update # ⛔️ NO create-drop - Los datos persisten
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  
  sql:
    init:
      mode: never # No ejecutar scripts SQL automáticos

# Database Seeding Configuration
sigmagym:
  seed:
    enabled: true # Habilitar seeding en desarrollo
  features:
    waitlist:
      enabled: false

