package com.sigma.gym.DTOs;

import com.sigma.gym.model.WorkoutPlanStatus;
import lombok.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import com.sigma.gym.controllers.user.UserDTO;

/**
 * DTO for WorkoutPlan operations with enhanced functionality
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class WorkoutPlanDTO {
    
    private Long id;
    
    @NotBlank(message = "Name is required")
    @Size(max = 100, message = "Name must not exceed 100 characters")
    private String name;
    
    private String slug; // Read-only, generated by service
    
    private WorkoutPlanStatus status;
    
    @Size(max = 500, message = "Goal must not exceed 500 characters")
    private String goal;
    
    @Size(max = 1000, message = "Description must not exceed 1000 characters")
    private String description;
    
    private LocalDate startDate;
    
    private LocalDate endDate;
    
    @Size(max = 50, message = "Difficulty must not exceed 50 characters")
    private String difficulty;
    
    @Size(max = 1000, message = "Notes must not exceed 1000 characters")
    private String notes;
    
    // Read-only fields
    private Long ownerId;
    private LocalDate createdAt;
    private LocalDateTime updatedAt;
    private Long version;
    
    // Legacy fields - for backward compatibility
    private UserDTO trainer; // DEPRECATED: use owner instead
    private List<RoutineDTO> routines; // DEPRECATED: use planDays instead
    private List<UserDTO> members; // Users following the plan
    
    // New enhanced fields
    private List<PlanDayDTO> planDays; // New structured days
    private Integer totalDays;
    private Boolean hasMembers;
}
